### ISSUE TITLE
The latest version of pyenv-win is 1.2.5

### ISSUE THREAD

**Issue by IvanaGyro** [bazzilic/ChocolateyPackages#10]
The latest version of pyenv-win is 1.2.5 now. Is it good to update this package?

**Comment by bazzilic** [comment]
Are you sure it is 1.2.5?

**Comment by IvanaGyro** [comment]
> 
> 
> Are you sure it is 1.2.5?

I'am sorry. I didn't notice that v1.2.5 is marked as pre-release.
