### ISSUE TITLE
VBoxVmService newer version

### ISSUE THREAD

**Issue by tunisiano187** [bazzilic/ChocolateyPackages#12]
Hi!

The version of VboxVmService in the package registry is 6.0
The latest version is 6.1 : https://github.com/onlyfang/VBoxVmService/releases

In the same time can you close this issue? Thank you.
https://github.com/dtgm/chocolatey-packages/issues/237

**Comment by bazzilic** [comment]
Apparently, v6.1 was hidden at some point because iot was triggering automatic antivirus checks at Chocolatey backend. I am following up with Chocolatey admins on that. Closing the issue.
