### ISSUE TITLE
Pyenv-win: https://github.com/pyenv-win/ChocolateyPackages

### ISSUE THREAD

**Issue by kirankotari** [bazzilic/ChocolateyPackages#14]
Hi Bazzilic,

We have created a repo for you in pyenv-win, do you wish to contribute there?
Let us know

@dedale @kirankotari

**Comment by bazzilic** [comment]
I'll continue to work in my repo for now.

**Comment by kirankotari** [comment]
@bazzilic any plans of giving maintenance access to pyenv-win chocolatey package to any one of us
@kirankotari  @dedale 
my id: `kkotari`

**Comment by bazzilic** [comment]
Do you have anything in particular that you would like to add?
I maintain this package for the only reason that I occasionally use pyenv-win and I like to install everything from Chocolatey. Let me know if you want to adopt the package and continue supporting it and uploading to Chocolatey. If you don't, it's fine, it's automated on my end, so it doesn't take a lot of effort to upload it occasionally.

**Comment by kirankotari** [comment]
When we do a new release via GitHub we have an action to upload the latest version to PyPI. Note:- That how we wanted to keeping the releases in sync across all platforms. 

Currently we are doing for PyPI. Now we wanted to bring the same approach to Chocolatey. You be the Owner of Chocolatey package allow us to push the latest release to Chocolatey along with PyPI with GitHub Actions. 

Check this: https://github.com/pyenv-win/pyenv-win/blob/master/.github/workflows/publish.yml 
Similarly we are planning to write another action to push the latest releases to Chocolatey.

**Comment by kirankotari** [comment]
If this approaches works, there are a lot of other platforms I wanted you to explore if you have time. 
```
scoop
winget
...
```

**Comment by bazzilic** [comment]
I see. Here's what we can do. I will add you as a package maintainer on Chocolatey.org (lmk your username there). This will allow you to get an API key to upload the package from the github action.

Then, I think, best course of action will be if you fork the repo and continue maintaining it. Generally, there isn't much to maintain, the installation script just downloads the release from github and sets PATH variables and that's it. I don't use scoop or winget, so I don't think I'll make packages for those platforms.

Let me know your thoughts!

**Comment by bazzilic** [comment]
@kirankotari I added you as a maintainer on Chocolatey, I think you need to accept it somehow.

![image](https://user-images.githubusercontent.com/1805832/121302419-3cc1a600-c92c-11eb-9af2-decfc634a081.png)

**Comment by kirankotari** [comment]
> @kirankotari I added you as a maintainer on Chocolatey, I think you need to accept it somehow.
> 
> ![image](https://user-images.githubusercontent.com/1805832/121302419-3cc1a600-c92c-11eb-9af2-decfc634a081.png)

Thanks @bazzilic I am looking out where can i find the request to accept it. do you have any ref. link please forward.

**Comment by kirankotari** [comment]
@bazzilic Can you request again, The Chocolatey team say I need to receive a email to accept the invite, which I haven't received to accept.

**Comment by kirankotari** [comment]
@bazzilic Thank you got the access 👍
