### ISSUE TITLE
pyenv-win: Setting system PATH when installing to USERPROFILE can cause permissions problems

### ISSUE THREAD

**Issue by davetapley** [bazzilic/ChocolateyPackages#15]
I _assume_ that 3fdb41235a1693be04957007944abc72e3e5f002 was for #13, if so then this is a follow up to that.

This is also related to https://github.com/pyenv-win/pyenv-win/issues/321 insomuch as I noticed this while debugging that.

My concern is with: https://github.com/bazzilic/ChocolateyPackages/blob/3fdb41235a1693be04957007944abc72e3e5f002/pyenv-win/chocolateyInstall.ps1.template#L8-L11

We are setting a `Machine` variable to reference a path under `USERPROFILE`, which would be _weird_ if you are not presently the user who originally installed, because it's unlikely you'll have permission to read `USERPROFILE`, despite it being referenced in your (inherited) `PATH`.

**Comment by bazzilic** [comment]
Good point. I'll close this in favor of #16.
