### ISSUE TITLE
VBoxVmService install script

### ISSUE THREAD

**Issue by jmcker** [bazzilic/ChocolateyPackages#2]
Hi! This repo is listed as the Package Source for the [VBoxVmService](https://chocolatey.org/packages/VBoxVmService) on Chocolatey, but the script doesn't seem to exist anymore.

I was able to find [dgam's repo](https://github.com/dtgm/chocolatey-packages/tree/master/automatic/vboxvmservice/tools), but it contained a somewhat older version of the script.

The VBoxVmService project moved from SourceForge to [GitHub](https://github.com/onlyfang/VBoxVmService), and there's a new version out. I'm trying to get it up and running on Chocolatey.

Any idea where the script is located to contribute to/who maintains it?

**Comment by bazzilic** [comment]
Hi! VBoxVmService was created manually. I added the files to the repo just now. I didn't have the time to switch the installation script over to github yet, if you'd like to make a PR to this repo it would be appreciated.

**Comment by bazzilic** [comment]
Hi @jmcker 

Something went wrong with the installer you suggested, installation times out, here's the log: https://gist.github.com/choco-bot/bb572d95908f7f6f7380dd38e46ce625

**Comment by jmcker** [comment]
Seems to be related to onlyfang/VBoxVmService#11. It installed fine on my production server, but hung with a dialog complaining about a missing DLL in the test environment provided by Chocolatey. The install succeeds in the test environment after dismissal of the error, but the dialog is causing the hang.

I'll take a look for a solution or reach out to the VBoxVmService team.

**Comment by bazzilic** [comment]
Does it perhaps need VC++ redistributable of some kind as a dependency? In particular, `vcredist2013` as per https://github.com/onlyfang/VBoxVmService/issues/11

**Comment by jmcker** [comment]
I tried that indeed. It resolves the dialog and the install succeeds, but the service fails to connect and work on Windows Server 2012 (the OS of choice for the Choco environment) as the issue mentions.

I'm not sure if this would be acceptable to release.

**Comment by bazzilic** [comment]
Does it work on newer Win Servers?

**Comment by jmcker** [comment]
Not sure yet. I had it working on Win 10 Pro.

**Comment by bazzilic** [comment]
I think it should be fine then, can you create a PR with the dependency?
