### ISSUE TITLE
pyenv-win still pointing to 1.2.2, but the latest is 1.2.4

### ISSUE THREAD

**Issue by kirankotari** [bazzilic/ChocolateyPackages#7]
@bazzilic pyenv-win still pointing to the older version of the GitHub master branch. Did you use "au" for chocolatey package? Which automatically takes the latest updates from GitHub.

**Comment by bazzilic** [comment]
No, I manually update the package when needed. I.e., I run the script and push the update to Chocolatey gallery.

**Comment by bazzilic** [comment]
I updated the script to use `.version` file and submitted the new version to Chocolatey 👍
