### ISSUE TITLE
Please update the package vim-console on chocolatey.org

### ISSUE THREAD

**Issue by aba-rechsteiner** [bazzilic/ChocolateyPackages#9]
@bazzilic we are waiting for the change "ftp to http" a4796dbd1fd34616c857d902a59feb508aaaba67

**Comment by aba-rechsteiner** [comment]
@jmcker @bazzilic any updates here?

**Comment by aba-rechsteiner** [comment]
@bazzilic ?

**Comment by bazzilic** [comment]
It is https now, the package is waiting for the review

![image](https://user-images.githubusercontent.com/1805832/76059086-f0651900-5fb8-11ea-9a5e-6807f1ba1813.png)

**Comment by aba-rechsteiner** [comment]
Yeah, I know. Can I help with the review?

**Comment by bazzilic** [comment]
If you are one of the package mods on Chocolatey. Otherwise, you can't :)
